proxy:
  container_name: proxy
  build: services/proxy
  ports:
    - 80:80
  environment:
    DOCKER_HOST:
    DOCKER_TLS_VERIFY:
    DOCKER_CERT_PATH:
  volumes:
    - ${DOCKER_CERT_PATH}:${DOCKER_CERT_PATH}

data:
  container_name: data
  build: services/data

beataml_postgres:
  container_name: beataml_postgres
  build: services/postgres
  environment:
    POSTGRES_USER: labkey
    POSTGRES_PASSWORD: labkey

beataml_dms:
  container_name: beataml_dms
  build: services/labkey
  volumes_from:
    - data
  environment:
    VIRTUAL_HOST: dms.beataml.ohsu.dev
    VIRTUAL_PORT: 8080
    DATABASE_USER: labkey
    DATABASE_PASSWORD: labkey
    DATABASE_CONNECTION_STRING: jdbc:postgresql://beataml_postgres/labkey
  volumes:
    - ./sites/dms.beataml.ohsu.dev:/site

oicr_postgres:
  container_name: oicr_postgres
  build: services/postgres
  environment:
    POSTGRES_USER: oicr
    POSTGRES_PASSWORD: oicr

oicr_dms:
  container_name: oicr_dms
  build: services/mywebsql
  environment:
    VIRTUAL_HOST: dms.boutros.oicr.dev
  volumes:
    - ./sites/dms.boutros.oicr.dev:/site

oicr_elasticsearch:
  container_name: oicr_elasticsearch
  build: services/elasticsearch
  environment:
    VIRTUAL_HOST: elasticsearch.oicr.ccc.dev
    VIRTUAL_PORT: 9200
  volumes:
    - ./sites/elasticsearch.oicr.ccc.dev:/site

ohsu_elasticsearch:
  container_name: ohsu_elasticsearch
  build: services/elasticsearch
  environment:
    VIRTUAL_HOST: elasticsearch.ohsu.ccc.dev
    VIRTUAL_PORT: 9200
  volumes:
    - ./sites/elasticsearch.ohsu.ccc.dev:/site

central_function_elasticsearch:
  container_name: central_function_elasticsearch
  build: services/elasticsearch
  environment:
    VIRTUAL_HOST: elasticsearch.central-function.ccc.dev
    VIRTUAL_PORT: 9200
  volumes:
    - ./sites/elasticsearch.central-function.ccc.dev:/site

central_function_galaxy:
  container_name: central_function_galaxy
  build: services/galaxy
  environment:
    VIRTUAL_HOST: galaxy.central-function.ccc.dev
    VIRTUAL_PORT: 8080
  volumes_from:
    - data

selenium:
  container_name: selenium
  build: services/selenium

dts:
  container_name: dts
  build: services/execution_engine
  environment:
    VIRTUAL_HOST: dts.exeuction-engine.central-function.ccc.dev
    VIRTUAL_PORT: 9510
  volumes:
    - ./sites/dts.central-function.ccc.dev:/site
  volumes_from:
    - data
  environment:
    AGENT_SCHEDULER_DRMAA_HOST: localhost
    AGENT_SCHEDULER_NONDRMAA_HOST: localhost
    DTS_DATABASE_HOST: dts_database

dts_database:
  container_name: dts_database
  image: mongo/3.0.8

dispatcher:
  container_name: dispatcher
  build: services/execution_engine
  environment:
    VIRTUAL_HOST: dispatcher.execution-engine.central-function.ccc.dev
    VIRTUAL_PORT: 8080
  volumes_from:
    - data
  volumes:
    - ./sites/dispatcher.central-function.ccc.dev:/site

agent:
  container_name: agent
  build: services/execution_engine
  environment:
    VIRTUAL_HOST: agent.execution-engine.central-function.ccc.dev
    VIRTUAL_PORT: 8080
  volumes_from:
    - data
  volumes:
    - ./sites/dispatcher.central-function.ccc.dev:/site

cromwell:
  container_name: cromwell
  build: services/execution_engine
  environment:
    VIRTUAL_HOST: cromwell.execution-engine.central-function.ccc.dev
    VIRTUAL_PORT: 8000
  volumes_from:
    - data
  volumes:
    - ./sites/cromwell.execution-engine.central-function.ccc.dev:/site

app_manager:
  container_name: app_manager
  build: services/app_repository
  environment:
    VIRTUAL_HOST: app-manager.central-function.ccc.dev
    VIRTUAL_PORT: 8081
  volumes_from:
    - data
  volumes:
    - ./sites/app-manager.central-function.ccc.dev:/site

container_manager:
  container_name: container_manager
  build: services/app_repository
  environment:
    VIRTUAL_HOST: container-manager.central-function.ccc.dev
    VIRTUAL_PORT: 5000
  volumes_from:
    - data
  volumes:
    - ./sites/container-manager.central-function.ccc.dev:/site
